/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ikZUwdc7As3DStD19u7teV

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariants_8GrdexOszGqE } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 8GRDEXOszGqE/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariants_8GrdexOszGqE
});
