/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ikZUwdc7As3DStD19u7teV
// Component: chOtdWAOBe7A

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: ikZUwdc7As3DStD19u7teV/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: ikZUwdc7As3DStD19u7teV/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: ikZUwdc7As3DStD19u7teV/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: chOtdWAOBe7A/css

import MenuIcon from "./icons/PlasmicIcon__Menu"; // plasmic-import: So0yqYnacOuZ/icon

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  powerApps?: Flex__<"div">;
  rectangle18?: Flex__<"div">;
  svg?: Flex__<"svg">;
  aiPsPowerApps11?: Flex__<"div">;
  rectangle15?: Flex__<"div">;
  aiPsSymbol34?: Flex__<"div">;
  aiPsPowerapps21?: Flex__<"div">;
  rectangle19?: Flex__<"div">;
  rectangle20?: Flex__<"div">;
  rectangle21?: Flex__<"div">;
  aiPsSymbol35?: Flex__<"div">;
};

export interface DefaultHomepageProps {
  className?: string;
}

const $$ = {};

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"powerApps"}
            data-plasmic-override={overrides.powerApps}
            className={classNames(projectcss.all, sty.powerApps)}
          >
            <div
              data-plasmic-name={"rectangle18"}
              data-plasmic-override={overrides.rectangle18}
              className={classNames(projectcss.all, sty.rectangle18)}
            />

            <MenuIcon
              data-plasmic-name={"svg"}
              data-plasmic-override={overrides.svg}
              className={classNames(projectcss.all, sty.svg)}
              role={"img"}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__iouIl
              )}
            >
              {"Projects"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__xaXw
              )}
            >
              {"Contact"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__la5CB
              )}
            >
              {"PowerStarter"}
            </div>
            <div
              data-plasmic-name={"aiPsPowerApps11"}
              data-plasmic-override={overrides.aiPsPowerApps11}
              className={classNames(projectcss.all, sty.aiPsPowerApps11)}
            />

            <div
              data-plasmic-name={"rectangle15"}
              data-plasmic-override={overrides.rectangle15}
              className={classNames(projectcss.all, sty.rectangle15)}
            />

            <div
              data-plasmic-name={"aiPsSymbol34"}
              data-plasmic-override={overrides.aiPsSymbol34}
              className={classNames(projectcss.all, sty.aiPsSymbol34)}
            />

            <div
              data-plasmic-name={"aiPsPowerapps21"}
              data-plasmic-override={overrides.aiPsPowerapps21}
              className={classNames(projectcss.all, sty.aiPsPowerapps21)}
            />

            <div
              data-plasmic-name={"rectangle19"}
              data-plasmic-override={overrides.rectangle19}
              className={classNames(projectcss.all, sty.rectangle19)}
            />

            <div
              data-plasmic-name={"rectangle20"}
              data-plasmic-override={overrides.rectangle20}
              className={classNames(projectcss.all, sty.rectangle20)}
            />

            <div
              data-plasmic-name={"rectangle21"}
              data-plasmic-override={overrides.rectangle21}
              className={classNames(projectcss.all, sty.rectangle21)}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__cMe8D
              )}
            >
              {"\u00a9 2025, Profound Inc. Build with tailwind"}
            </div>
            <div
              data-plasmic-name={"aiPsSymbol35"}
              data-plasmic-override={overrides.aiPsSymbol35}
              className={classNames(projectcss.all, sty.aiPsSymbol35)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "powerApps",
    "rectangle18",
    "svg",
    "aiPsPowerApps11",
    "rectangle15",
    "aiPsSymbol34",
    "aiPsPowerapps21",
    "rectangle19",
    "rectangle20",
    "rectangle21",
    "aiPsSymbol35"
  ],
  powerApps: [
    "powerApps",
    "rectangle18",
    "svg",
    "aiPsPowerApps11",
    "rectangle15",
    "aiPsSymbol34",
    "aiPsPowerapps21",
    "rectangle19",
    "rectangle20",
    "rectangle21",
    "aiPsSymbol35"
  ],
  rectangle18: ["rectangle18"],
  svg: ["svg"],
  aiPsPowerApps11: ["aiPsPowerApps11"],
  rectangle15: ["rectangle15"],
  aiPsSymbol34: ["aiPsSymbol34"],
  aiPsPowerapps21: ["aiPsPowerapps21"],
  rectangle19: ["rectangle19"],
  rectangle20: ["rectangle20"],
  rectangle21: ["rectangle21"],
  aiPsSymbol35: ["aiPsSymbol35"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  powerApps: "div";
  rectangle18: "div";
  svg: "svg";
  aiPsPowerApps11: "div";
  rectangle15: "div";
  aiPsSymbol34: "div";
  aiPsPowerapps21: "div";
  rectangle19: "div";
  rectangle20: "div";
  rectangle21: "div";
  aiPsSymbol35: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    powerApps: makeNodeComponent("powerApps"),
    rectangle18: makeNodeComponent("rectangle18"),
    svg: makeNodeComponent("svg"),
    aiPsPowerApps11: makeNodeComponent("aiPsPowerApps11"),
    rectangle15: makeNodeComponent("rectangle15"),
    aiPsSymbol34: makeNodeComponent("aiPsSymbol34"),
    aiPsPowerapps21: makeNodeComponent("aiPsPowerapps21"),
    rectangle19: makeNodeComponent("rectangle19"),
    rectangle20: makeNodeComponent("rectangle20"),
    rectangle21: makeNodeComponent("rectangle21"),
    aiPsSymbol35: makeNodeComponent("aiPsSymbol35"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
